server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost/search
    username: postgres
    password: 112358
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

